server:
   port: 8082

spring: 
   datasource: 
      url: jdbc:mysql://localhost:3306/vaccinationcentredb
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      show-sql: true 
      hibernate:
         ddl-auto: update
         database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   application:
      name: VACCINATION-CENTRE-SERVICE
      

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      vaccinationService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


#  retry:
#    instances:
#      userService:
#        maxRetryAttempts: 5
#        waitDuration: 10s










